extend type Mutation{
    """
    -auth admin, user
    """
    createTask(inputDescription:String!): Task
    """
    -auth admin, user
    """
    updateTask(input:UpdateTask): Task
    """
    -auth admin, user
    """
    deleteTask(taskID:ID!): Task
}