type JobArea {
    """
    -type ID
    """
    _id:ID!
    name:String
    """
    -type [ID]
    """
    jobTitles: EdgeJobTitle
    """
    -created
    """
    created:DateTime
    """
    -updated
    """
    updated:DateTime
}
type EdgeJobArea {
    """
    -bsonOmmit
    """
    edges:[JobArea]
    """
    -bsonOmmit
    """
    pageInfo:PageInfo
}