extend type Mutation{
    createUser(input:CreateUser): User
    """
    -auth admin, user
    """
    updateUser(input:UpdateUser): User
    """
    -auth admin, user
    """
    deleteUser(_id: ID!): User 
    resetUserPassword(input:ResetUserPassword): User
    """"
    -auth root
    """
    assignPermissions(input:PermissionsInput): User
    """"
    -auth root
    """
    removePermissions(input:PermissionsInput): User
}
