enum OperationEnum {
    create
    read
    update
    delete
}

enum ModuleNameEnum {
    collegeDependency
    device
    jobArena
    jobTitle
    resolverActivity
    task
    technicalDiagnosis
    user
}