enum OperationEnum {
    create
    read
    update
    delete
}

enum ModuleNameEnum {
    CollegeDependency
    Device
    JobArea
    JobTitle
    ResolverActivity
    Task
    TechnicalDiagnosis
    User
}