input CreateDevice {
   transferEvidence: SetDeviceTransferEvidence
   deviceInfo: DeviceInfo
}

input DeviceInfo {
   placeOfCare:PlaceOfCareEnum!
   collegeDependency:ID!
   isSupport:Boolean!
   assetCode:String
   serialCode:String
   type:String
   model:String
   #groupID:ID
   observations:[SetDeviceObservationInput!]
   """
   -must set this if the place of care is local
   """
   localTechnicalDiagnosis:[CreateTechnicalDiagnosis!]

}

input UpdateDevice {  
   """
   -type ID
   """
   _id: ID!
   deviceInfo: DeviceInfo
   transferEvidence:SetDeviceTransferEvidence
}