input CreateDevice {
   transferEvidence: SetDeviceTransferEvidence
   collegeDependency:ID!
   deviceInfo: [CreateDeviceInfo!]!
}

input CreateDeviceInfo {
   placeOfCare:PlaceOfCareEnum!
   isSupport:Boolean!
   assetCode:String
   serialCode:String
   type:String
   model:String
   #groupID:ID
   observations:[SetDeviceObservationInput!]
   """
   -must set this if the place of care is local
   """
   localTechnicalDiagnosis:[CreateTechnicalDiagnosis!]
}

input UpdateDevice {  
   """
   -type ID
   """
   _id: ID!
   collegeDependency: ID
   transferEvidence:SetDeviceTransferEvidence
   assetCode:String
   serialCode:String
   type:String
   model:String
   #groupID:ID
   observations:[SetDeviceObservationInput!]
   supportStatus:SupportStatusEnum
}