input CreateDevice {
   transferEvidence: SetDeviceTransferEvidence
   collegeDependency:ID!
   deviceInfo: [CreateDeviceInfo!]!
   placeOfCare:PlaceOfCareEnum!
}

input CreateDeviceInfo {
   isSupport:Boolean!
   assetCode:String
   serialCode:String
   type:String
   estimatedDeliveryDate: DateTime
   model:String
   observations:[SetDeviceObservationInput!]
   """
   -must set this if the place of care is local
   """
   localTechnicalDiagnosis:[CreateTechnicalDiagnosis!]
}

input UpdateDevice {  
   """
   -type ID
   """
   _id: ID!
   collegeDependency: ID
   assetCode:String
   serialCode:String
   type:String
   model:String
   observations:[SetDeviceObservationInput!]
   currentSupportStatus:SupportStatusEnum
}

input DeliveryDevicesInput {
   transferEvidence:SetDeviceTransferEvidence!
   deviceIDs: [ID!]!
}